spring :
       security :
                user : 
                   name : shri
                   
                password : shri   
                
                

server:
         port:  8091                      
                           
                                          